### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Pub4Game** [CamoSplatty14/MoreCommands#1]
Необработанное исключение при выполнении команды 'last history' в last: Undefined property: GlaciercreepsMC\morecommands\LastCommandListener::$emptyErrorMsg

**Comment by CamoSplatty14** [comment]
@Pub4Game О, спасибо за рассказывал мне! Я положу еще одно обновление, чтобы исправить это.

**Comment by Pub4Game** [comment]
@CamoSplatty14 Please add /fly /god . Thank you!

**Comment by RandomAltThingy** [comment]
Tf lel

**Comment by CamoSplatty14** [comment]
@RandomAltThingy He was speaking russian and informed me of an error; anyway, used google translate, haha

**Comment by Pub4Game** [comment]
@CamoSplatty14 :((

**Comment by CamoSplatty14** [comment]
@Pub4Game Да, извините, но я не понимаю по-русски. Спасибо, что рассказал мне ошибки! Кроме того, я должен упомянуть, плагин EssentialsPE имеет две команды, которые вы просили за "/ бог» и «/ ТПА".

**Comment by Pub4Game** [comment]
@CamoSplatty14 Я бы хотел использовать ваш плагин с этими командами /god /v
