### ISSUE TITLE
Can you fix this?.it doesnt work for 0.12 there is an error

### ISSUE THREAD

**Issue by SoyPro** [CamoSplatty14/MoreCommands#5]
[Server][21:05:09][Server thread/CRITICAL]: "Could not pass event 'pocketmine\event\player\PlayerCommandPreprocessEvent' to 'MoreCommands v 1.1.3': illegal offset type un isset or empty on GlacierscreepsMC\morecommands\LastCommandListener
[Server][21:06:15][Server thread/WARNING]: RunTimeException: "illegal offset type in isset or empty" (E_WARNING) in "/plugin-743.phar/src/GlaciercreepsMC/morecommands/LastCommandListener" at line 44

**Comment by Pub4Game** [comment]
Use the source from GitHub and build the plugin

**Comment by RandomAltThingy** [comment]
To do this, download the DevTools plugin, and put it in the plugin folder of your server.
Next, download this repo as a zip and then extract it. After that, rename the extracted repo to  whatever you want, lets say you named it *"sup"*.

Put this extracted folder into the plugins folder and start the server.
Once the server is started, in console type the following:
<code>makeplugin sup</code>. Make sure to replace 'sup' with whatever you named the folder.

Now the plugin should work fine! Find it in your DevTools folder inside the plugin folder, just drag out the phar to the plugin folder.

**Comment by SoyPro** [comment]
I unistall this plugin. i have essentialsPE installed but with what permission players can get creative?. 
With essentials.gmc or essentials.gamemode because with permission gamemode nothing happen.when i put in the chat /gamemode 1,it show me:[Error]:please specific a valid gamemode.i intent with essentials.gmc but players havent permissions.so explain me how i can give them permission for creative with essentialsPE

**Comment by SoyPro** [comment]
And randomaltthingy if you are the helper of CamoSplatty14 please do it yourself,dont explain other people because maybe other people dont know how to do it.thanks!

**Comment by CamoSplatty14** [comment]
@SoyPro Hello, sorry I didn't answer. I'll  try to see what may be causing the error and will update the plugin as soon as I find a fix.
@RandomAltThingy If take a look at the error, it is already a phar; and the name "plugin-#" indicates he downloaded it from the [offical plugin area](https://forums.pocketmine.net/plugins/). Which means he shouldn't have to build it because technically *I* did a while ago when I uploaded the plugin. There is a bug that I/we have to fix.

**Comment by RandomAltThingy** [comment]
@CamoSplatty14 Actually, @Pub4game said to compiler from github so I gave steps on how to.

**Comment by CamoSplatty14** [comment]
@RandomAltThingy That's fine, I'm just saying that compiling it from github wouldn't make a difference since it's the same code as in the downloaded phar.

**Comment by RandomAltThingy** [comment]
The github one has more <code>->toString()</code> methods.

**Comment by CamoSplatty14** [comment]
@RandomAltThingy Ah, I forgot about that. I'll look into it soon, as I can't right now.

**Comment by CamoSplatty14** [comment]
Alright guys, the problem should be fixed. I'm now using array_key_exists() rather than isset(). Also, I'm removing the toString() methods, @RandomAltThingy. That doesn't exist for uuid's in the current api, and plus, the uuid is already a string.
