### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Pub4Game** [CamoSplatty14/MoreCommands#6]
[Server thread/WARNING]: RuntimeException: "Illegal offset type" (E_WARNING) in "/MoreCommands_v1.1.3.phar/src/GlaciercreepsMC/morecommands/LastCommandListener" at line 45

**Comment by RandomAltThingy** [comment]
@CamoSplatty14 Can't fix now, here's the error line:
https://github.com/CamoSplatty14/MoreCommands/blob/master/src/GlaciercreepsMC/morecommands/LastCommandListener.php#L45

**Comment by CamoSplatty14** [comment]
@RandomAltThingy I was also trying to figure it out, it's fine. Although, the error stated [here](https://github.com/CamoSplatty14/MoreCommands/issues/5#issuecomment-149020175) is [line 44](https://github.com/CamoSplatty14/MoreCommands/blob/master/src/GlaciercreepsMC/morecommands/LastCommandListener.php#L44). So, it seems I must use some other way of checking if the array element for the command issuer exists.

@Pub4Game Where did you get that error from? Was it actually mentioned in the server console or is that from the previous issue mentioned above?

**Comment by RandomAltThingy** [comment]
@Pub4game Also, please give some steps to reproduce .

**Comment by Pub4Game** [comment]
My players have used commands to your plugin and then I looking in the console this error there were 44 and 45 line

Sorry my bad english

**Comment by CamoSplatty14** [comment]
Alright guys, the problem should be fixed. I'm now using array_key_exists() rather than isset(). I'll update soon, @Pub4Game.
